import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex md:min-h-screen flex-col justify-between py-4 w-full">
					<nav></nav>
					{children}
					<footer>
						<p className="text-center text-slate-300 font-medium text-xs">
							&copy; {new Date().getFullYear()} By Rava
						</p>
					</footer>
				</div>
			</body>
		</html>
	);
}
